-- ACTUALIZACIÓN DE ESQUEMA: INSUMOS (MÁS VALORES NUTRICIONALES)
-- Ejecuta esto en el SQL Editor de Supabase.

ALTER TABLE insumos 
ADD COLUMN IF NOT EXISTS saturadas NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS trans NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS colesterol NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS azucares NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS fibra NUMERIC DEFAULT 0;
